-- List of plugin configs to import

require('plugins_config.lualine')
require('plugins_config.comment')
require('plugins_config.indent_blankline')
require('plugins_config.gitsigns')
require('plugins_config.telescope')
require('plugins_config.treesitter')
require('plugins_config.nvimtree')
require('plugins_config.lsp')
require('plugins_config.lsp_signature')
require('plugins_config.nvim-dap')
require('plugins_config.nvim-dap-ui')
require('plugins_config.vimtex')
require('plugins_config.ultisnips')
require('plugins_config.nvim-scrollbar')
require('plugins_config.vim-illuminate')
require('plugins_config.nvim-navic')
require('plugins_config.vim-markdown')
